import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Drive Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        {children}
        <p className="text-center clear-both font-semibold py-8">Desenvolvido com ❤️ por <Link href="https://www.mystdev.com.br/" target="_blank" rel="noopener noreferrer" className="text-blue-100">Myst1 Dev</Link></p>
    </>
  );
}
