import { Footer } from "@/components/blog/footer";
import type { Metadata } from "next";
import Providers from "@/services/store/Providers";

export const metadata: Metadata = {
  title: "Drive Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers>
        {children}
        <Footer />
      </Providers>
    </>
  );
}
